# Generated by Django 6.0.5 on 2026-05-21 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('raw_file', models.FileField(upload_to='raw_datasets/')),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.IntegerField()),
                ('peak_time', models.FloatField(blank=True, null=True)),
                ('peak_amplitude', models.FloatField(blank=True, null=True)),
                ('trough_time', models.FloatField(blank=True, null=True)),
                ('trough_amplitude', models.FloatField(blank=True, null=True)),
                ('rise_time', models.FloatField(blank=True, null=True)),
                ('fall_time', models.FloatField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='api.sensordataset')),
            ],
            options={
                'ordering': ['cycle_number'],
            },
        ),
    ]
